export const SET_CARBRAND = 'SET_CARBRAND'
export const SET_ANIMATETYPE = 'SET_ANIMATETYPE'
export const SET_ADDCAR = 'SET_ADDCAR'
export const SET_MYCAR = 'SET_MYCAR'
export const SET_DEFAULTCAR = 'SET_DEFAULTCAR'
export const SET_CITYINFO = 'SET_CITYINFO'
export const SET_CITYLIST = 'SET_CITYLIST'
export const SET_STORELIST = 'SET_STORELIST'
export const SET_SERACHHIS = 'SET_SERACHHIS'
export const SET_SERACHINFO = 'SET_SERACHINFO'
export const SET_DEFAULTSTORE_ID = 'SET_DEFAULTSTORE_ID'
export const SET_MY_SERVER = 'SET_MY_SERVER'
export const SET_ALL_SERVER_LIST = 'SET_ALL_SERVER_LIST'
export const SET_STATIC_SERVER_LIST = 'SET_STATIC_SERVER_LIST'
export const SET_UPDATE_ORDER = 'SET_UPDATE_ORDER'
export const SET_ORDER_INFO = 'SET_ORDER_INFO'

export const SET_REPAIR_ORDER = 'SET_REPAIR_ORDER'
export const SET_LOADING_STATE = 'SET_LOADING_STATE'

export const MODIFY_CITYINFO = 'MODIFY_CITYINFO'
export const MODIFY_MYCAR = 'MODIFY_MYCAR'
export const MODIFY_ALL_SERVER_LIST = 'MODIFY_ALL_SERVER_LIST'
export const MODIFY_STATIC_SERVER_LIST = 'MODIFY_STATIC_SERVER_LIST'
export const MODIFY_STATIC_SERVER_PARTINFO = 'MODIFY_STATIC_SERVER_PARTINFO'
export const MODIFY_ALL_SETVER_PARTINFO = 'MODIFY_ALL_SETVER_PARTINFO'
export const MODIFY_ORDER_LIST = 'MODIFY_ORDER_LIST'

export const DELETE_MYCAR = 'DELETE_MYCAR'
export const DELETE_SERACHHIS = 'DELETE_SERACHHIS'
export const DELETE_ALL_SERVER = 'DELETE_ALL_SERVER'
export const DELETE_ORDER_LIST = 'DELETE_ORDER_LIST'

export const DELETE_REPAIR_ORDER = 'DELETE_REPAIR_ORDER'
export const DELETE_UPDATE_ORDER = 'DELETE_UPDATE_ORDER'

// 用户信息
export const SET_USER_INFO = 'SET_USER_INFO'
export const DELETE_USER_INFO = 'DELETE_USER_INFO'
// 服务选择车辆信息
export const SET_SELECTCAR = 'SET_SELECTCAR'

// 记录新服务加载次数
export const SET_ADD_NEW_SERVER_LOAD_NUM = 'SET_ADD_NEW_SERVER_LOAD_NUM'
// 服务信息详情列表
export const SET_SELE_SERVERS_INFO = 'SET_SELE_SERVERS_INFO'
export const MODIFY_SELE_SERVERS_INFO = 'MODIFY_SELE_SERVERS_INFO'
// 检测单信息
export const SET_CHECKS_OBJ = 'SET_CHECKS_OBJ'
