export const SET_CARBRAND = 'SET_CARBRAND'
export const SET_ANIMATETYPE = 'SET_ANIMATETYPE'
export const SET_ADDCAR = 'SET_ADDCAR'
export const SET_MYCAR = 'SET_MYCAR'
export const SET_DEFAULTCAR = 'SET_DEFAULTCAR'
export const SET_CITYINFO = 'SET_CITYINFO'

export const MODIFY_CITYINFO = 'MODIFY_CITYINFO'
export const MODIFY_MYCAR = 'MODIFY_MYCAR'

export const DELETE_MYCAR = 'DELETE_MYCAR'
